// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop.h for the primary calling header

#ifndef VERILATED_VTOP___024ROOT_H_
#define VERILATED_VTOP___024ROOT_H_  // guard

#include "verilated.h"


class Vtop__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtop___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s0;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s3;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s6;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s11;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s13;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s44;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s56;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s68;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s80;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s83;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s84;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s89;
        VL_IN8(CLR,0,0);
        VL_IN8(MIN_ADV,0,0);
        VL_IN8(HR_ADV,0,0);
        VL_IN8(SETUP_ALARM,0,0);
        VL_IN8(SETUP_TIME,0,0);
        VL_IN8(CLK,0,0);
        VL_IN8(ALARM_EN,0,0);
        VL_IN8(DAY_ADV,0,0);
        VL_IN8(WEEK_ADV,0,0);
        VL_IN8(MONTH_ADV,0,0);
        VL_IN8(YEAR_ADV,0,0);
        VL_OUT8(SECONDS,6,0);
        VL_OUT8(MINUTES,6,0);
        VL_OUT8(HOURS,3,0);
        VL_OUT8(ALARM_MINUTES,6,0);
        VL_OUT8(ALARM_HOURS,3,0);
        VL_OUT8(DAYS,3,0);
        VL_OUT8(WEEKS,1,0);
        VL_OUT8(MONTHS,3,0);
        VL_OUT8(ALARM_DAYS,3,0);
        VL_OUT8(ALARM_WEEKS,1,0);
        VL_OUT8(ALARM_MONTHS,3,0);
        VL_OUT8(BUZZ,0,0);
        VL_OUT8(YEARS,3,0);
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__CLR;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__MIN_ADV;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__HR_ADV;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__SETUP_ALARM;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__SETUP_TIME;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__CLK;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__ALARM_EN;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DAY_ADV;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__WEEK_ADV;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__MONTH_ADV;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__YEAR_ADV;
        CData/*6:0*/ FrenchRepublicanCalendarAlarmClock__DOT__SECONDS;
        CData/*6:0*/ FrenchRepublicanCalendarAlarmClock__DOT__MINUTES;
        CData/*3:0*/ FrenchRepublicanCalendarAlarmClock__DOT__HOURS;
        CData/*6:0*/ FrenchRepublicanCalendarAlarmClock__DOT__ALARM_MINUTES;
        CData/*3:0*/ FrenchRepublicanCalendarAlarmClock__DOT__ALARM_HOURS;
        CData/*3:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DAYS;
        CData/*1:0*/ FrenchRepublicanCalendarAlarmClock__DOT__WEEKS;
        CData/*3:0*/ FrenchRepublicanCalendarAlarmClock__DOT__MONTHS;
        CData/*3:0*/ FrenchRepublicanCalendarAlarmClock__DOT__ALARM_DAYS;
        CData/*1:0*/ FrenchRepublicanCalendarAlarmClock__DOT__ALARM_WEEKS;
        CData/*3:0*/ FrenchRepublicanCalendarAlarmClock__DOT__ALARM_MONTHS;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__BUZZ;
        CData/*3:0*/ FrenchRepublicanCalendarAlarmClock__DOT__YEARS;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s1;
        CData/*6:0*/ FrenchRepublicanCalendarAlarmClock__DOT__SECONDS_temp;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s2;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s4;
    };
    struct {
        CData/*6:0*/ FrenchRepublicanCalendarAlarmClock__DOT__MINUTES_temp;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s5;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s7;
        CData/*3:0*/ FrenchRepublicanCalendarAlarmClock__DOT__HOURS_temp;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s8;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s9;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s10;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s12;
        CData/*6:0*/ FrenchRepublicanCalendarAlarmClock__DOT__ALARM_MINUTES_temp;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s14;
        CData/*3:0*/ FrenchRepublicanCalendarAlarmClock__DOT__ALARM_HOURS_temp;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s15;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s16;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s17;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s18;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s19;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s20;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s21;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s22;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s23;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s24;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s25;
        CData/*6:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s26;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s27;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s28;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s29;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s30;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s31;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s32;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s33;
        CData/*6:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s34;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s35;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s36;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s37;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s38;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s39;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s40;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s41;
        CData/*6:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s42;
        CData/*3:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s43;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s45;
        CData/*3:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DAYS_temp;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s46;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s47;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s48;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s49;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s50;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s51;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s52;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s53;
        CData/*6:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s54;
        CData/*3:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s55;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s57;
        CData/*1:0*/ FrenchRepublicanCalendarAlarmClock__DOT__WEEKS_temp;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s58;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s59;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s60;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s61;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s62;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s63;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s64;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s65;
        CData/*6:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s66;
        CData/*1:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s67;
    };
    struct {
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s69;
        CData/*3:0*/ FrenchRepublicanCalendarAlarmClock__DOT__MONTHS_temp;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s70;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s71;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s72;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s73;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s74;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s75;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s76;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s77;
        CData/*6:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s78;
        CData/*3:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s79;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s81;
        CData/*3:0*/ FrenchRepublicanCalendarAlarmClock__DOT__ALARM_DAYS_temp;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s82;
        CData/*1:0*/ FrenchRepublicanCalendarAlarmClock__DOT__ALARM_WEEKS_temp;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s85;
        CData/*3:0*/ FrenchRepublicanCalendarAlarmClock__DOT__ALARM_MONTHS_temp;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s86;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s87;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s88;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s90;
        CData/*3:0*/ FrenchRepublicanCalendarAlarmClock__DOT__YEARS_temp;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s91;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s92;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s93;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s94;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s95;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s96;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s97;
        CData/*6:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s98;
        CData/*6:0*/ FrenchRepublicanCalendarAlarmClock__DOT__s99;
        CData/*6:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i0__DOT__out;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i0__DOT__ovf;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i0__DOT__C;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i0__DOT__en;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i0__DOT__clr;
        CData/*6:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i0__DOT__count;
        CData/*6:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i1__DOT__out;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i1__DOT__ovf;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i1__DOT__C;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i1__DOT__en;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i1__DOT__clr;
        CData/*6:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i1__DOT__count;
        CData/*3:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i2__DOT__out;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i2__DOT__ovf;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i2__DOT__C;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i2__DOT__en;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i2__DOT__clr;
        CData/*3:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i2__DOT__count;
        CData/*3:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i3__DOT__out;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i3__DOT__ovf;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i3__DOT__C;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i3__DOT__en;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i3__DOT__clr;
        CData/*3:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i3__DOT__count;
        CData/*1:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i4__DOT__out;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i4__DOT__ovf;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i4__DOT__C;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i4__DOT__en;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i4__DOT__clr;
        CData/*1:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i4__DOT__count;
        CData/*3:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i5__DOT__out;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i5__DOT__ovf;
    };
    struct {
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i5__DOT__C;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i5__DOT__en;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i5__DOT__clr;
        CData/*3:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i5__DOT__count;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__Mux_2x1_NBits_i6__DOT__sel;
        CData/*6:0*/ FrenchRepublicanCalendarAlarmClock__DOT__Mux_2x1_NBits_i6__DOT__in_0;
        CData/*6:0*/ FrenchRepublicanCalendarAlarmClock__DOT__Mux_2x1_NBits_i6__DOT__in_1;
        CData/*6:0*/ FrenchRepublicanCalendarAlarmClock__DOT__Mux_2x1_NBits_i6__DOT__out;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__Mux_2x1_NBits_i7__DOT__sel;
        CData/*3:0*/ FrenchRepublicanCalendarAlarmClock__DOT__Mux_2x1_NBits_i7__DOT__in_0;
        CData/*3:0*/ FrenchRepublicanCalendarAlarmClock__DOT__Mux_2x1_NBits_i7__DOT__in_1;
        CData/*3:0*/ FrenchRepublicanCalendarAlarmClock__DOT__Mux_2x1_NBits_i7__DOT__out;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__Mux_2x1_NBits_i8__DOT__sel;
        CData/*3:0*/ FrenchRepublicanCalendarAlarmClock__DOT__Mux_2x1_NBits_i8__DOT__in_0;
        CData/*3:0*/ FrenchRepublicanCalendarAlarmClock__DOT__Mux_2x1_NBits_i8__DOT__in_1;
        CData/*3:0*/ FrenchRepublicanCalendarAlarmClock__DOT__Mux_2x1_NBits_i8__DOT__out;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__Mux_2x1_NBits_i9__DOT__sel;
        CData/*1:0*/ FrenchRepublicanCalendarAlarmClock__DOT__Mux_2x1_NBits_i9__DOT__in_0;
        CData/*1:0*/ FrenchRepublicanCalendarAlarmClock__DOT__Mux_2x1_NBits_i9__DOT__in_1;
        CData/*1:0*/ FrenchRepublicanCalendarAlarmClock__DOT__Mux_2x1_NBits_i9__DOT__out;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__Mux_2x1_NBits_i10__DOT__sel;
        CData/*3:0*/ FrenchRepublicanCalendarAlarmClock__DOT__Mux_2x1_NBits_i10__DOT__in_0;
        CData/*3:0*/ FrenchRepublicanCalendarAlarmClock__DOT__Mux_2x1_NBits_i10__DOT__in_1;
        CData/*3:0*/ FrenchRepublicanCalendarAlarmClock__DOT__Mux_2x1_NBits_i10__DOT__out;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__Mux_2x1_NBits_i11__DOT__sel;
        CData/*6:0*/ FrenchRepublicanCalendarAlarmClock__DOT__Mux_2x1_NBits_i11__DOT__in_0;
        CData/*6:0*/ FrenchRepublicanCalendarAlarmClock__DOT__Mux_2x1_NBits_i11__DOT__in_1;
        CData/*6:0*/ FrenchRepublicanCalendarAlarmClock__DOT__Mux_2x1_NBits_i11__DOT__out;
        CData/*6:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i12__DOT__out;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i12__DOT__ovf;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i12__DOT__C;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i12__DOT__en;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i12__DOT__clr;
        CData/*6:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i12__DOT__count;
        CData/*3:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i13__DOT__out;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i13__DOT__ovf;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i13__DOT__C;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i13__DOT__en;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i13__DOT__clr;
        CData/*3:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i13__DOT__count;
        CData/*3:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i14__DOT__out;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i14__DOT__ovf;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i14__DOT__C;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i14__DOT__en;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i14__DOT__clr;
        CData/*3:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i14__DOT__count;
        CData/*1:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i15__DOT__out;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i15__DOT__ovf;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i15__DOT__C;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i15__DOT__en;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i15__DOT__clr;
        CData/*1:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i15__DOT__count;
        CData/*3:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i16__DOT__out;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i16__DOT__ovf;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i16__DOT__C;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i16__DOT__en;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i16__DOT__clr;
        CData/*3:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i16__DOT__count;
        CData/*3:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i17__DOT__out;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i17__DOT__ovf;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i17__DOT__C;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i17__DOT__en;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i17__DOT__clr;
        CData/*3:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i17__DOT__count;
    };
    struct {
        CData/*6:0*/ FrenchRepublicanCalendarAlarmClock__DOT__CompUnsigned_i18__DOT__a;
        CData/*6:0*/ FrenchRepublicanCalendarAlarmClock__DOT__CompUnsigned_i18__DOT__b;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__CompUnsigned_i18__DOT____03e;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__CompUnsigned_i18__DOT____03d;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__CompUnsigned_i18__DOT____03c;
        CData/*3:0*/ FrenchRepublicanCalendarAlarmClock__DOT__CompUnsigned_i19__DOT__a;
        CData/*3:0*/ FrenchRepublicanCalendarAlarmClock__DOT__CompUnsigned_i19__DOT__b;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__CompUnsigned_i19__DOT____03e;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__CompUnsigned_i19__DOT____03d;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__CompUnsigned_i19__DOT____03c;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i20__DOT____030;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i20__DOT____031;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i20__DOT____032;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i20__DOT____033;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i20__DOT____034;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i20__DOT____035;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i20__DOT____036;
        CData/*6:0*/ FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i20__DOT__temp;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i21__DOT____030;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i21__DOT____031;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i21__DOT____032;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i21__DOT____033;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i21__DOT____034;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i21__DOT____035;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i21__DOT____036;
        CData/*6:0*/ FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i21__DOT__temp;
        CData/*3:0*/ FrenchRepublicanCalendarAlarmClock__DOT__CompUnsigned_i22__DOT__a;
        CData/*3:0*/ FrenchRepublicanCalendarAlarmClock__DOT__CompUnsigned_i22__DOT__b;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__CompUnsigned_i22__DOT____03e;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__CompUnsigned_i22__DOT____03d;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__CompUnsigned_i22__DOT____03c;
        CData/*1:0*/ FrenchRepublicanCalendarAlarmClock__DOT__CompUnsigned_i23__DOT__a;
        CData/*1:0*/ FrenchRepublicanCalendarAlarmClock__DOT__CompUnsigned_i23__DOT__b;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__CompUnsigned_i23__DOT____03e;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__CompUnsigned_i23__DOT____03d;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__CompUnsigned_i23__DOT____03c;
        CData/*3:0*/ FrenchRepublicanCalendarAlarmClock__DOT__CompUnsigned_i24__DOT__a;
        CData/*3:0*/ FrenchRepublicanCalendarAlarmClock__DOT__CompUnsigned_i24__DOT__b;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__CompUnsigned_i24__DOT____03e;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__CompUnsigned_i24__DOT____03d;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__CompUnsigned_i24__DOT____03c;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i25__DOT____030;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i25__DOT____031;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i25__DOT____032;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i25__DOT____033;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i25__DOT____034;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i25__DOT____035;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i25__DOT____036;
        CData/*6:0*/ FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i25__DOT__temp;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i26__DOT____030;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i26__DOT____031;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i26__DOT____032;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i26__DOT____033;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i26__DOT____034;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i26__DOT____035;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i26__DOT____036;
        CData/*6:0*/ FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i26__DOT__temp;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i27__DOT____030;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i27__DOT____031;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i27__DOT____032;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i27__DOT____033;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i27__DOT____034;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i27__DOT____035;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i27__DOT____036;
    };
    struct {
        CData/*6:0*/ FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i27__DOT__temp;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i28__DOT____030;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i28__DOT____031;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i28__DOT____032;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i28__DOT____033;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i28__DOT____034;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i28__DOT____035;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i28__DOT____036;
        CData/*6:0*/ FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i28__DOT__temp;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i29__DOT____030;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i29__DOT____031;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i29__DOT____032;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i29__DOT____033;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i29__DOT____034;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i29__DOT____035;
        CData/*0:0*/ FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i29__DOT____036;
        CData/*6:0*/ FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i29__DOT__temp;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__FrenchRepublicanCalendarAlarmClock__DOT__s0__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__FrenchRepublicanCalendarAlarmClock__DOT__s11__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__FrenchRepublicanCalendarAlarmClock__DOT__s13__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__FrenchRepublicanCalendarAlarmClock__DOT__s80__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__FrenchRepublicanCalendarAlarmClock__DOT__s83__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__FrenchRepublicanCalendarAlarmClock__DOT__s84__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__FrenchRepublicanCalendarAlarmClock__DOT__s3__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__FrenchRepublicanCalendarAlarmClock__DOT__s6__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__FrenchRepublicanCalendarAlarmClock__DOT__s44__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__FrenchRepublicanCalendarAlarmClock__DOT__s56__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__FrenchRepublicanCalendarAlarmClock__DOT__s68__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__FrenchRepublicanCalendarAlarmClock__DOT__s89__0;
        CData/*0:0*/ __VactContinue;
        VL_OUT16(SEG_SECONDS,13,0);
        VL_OUT16(SEG_MINUTES,13,0);
        VL_OUT16(SEG_HOURS,13,0);
        VL_OUT16(SEG_DAYS,13,0);
        VL_OUT16(SEG_WEEKS,13,0);
        VL_OUT16(SEG_MONTHS,13,0);
        VL_OUT16(SEG_YEARS,13,0);
        SData/*13:0*/ FrenchRepublicanCalendarAlarmClock__DOT__SEG_SECONDS;
        SData/*13:0*/ FrenchRepublicanCalendarAlarmClock__DOT__SEG_MINUTES;
        SData/*13:0*/ FrenchRepublicanCalendarAlarmClock__DOT__SEG_HOURS;
        SData/*13:0*/ FrenchRepublicanCalendarAlarmClock__DOT__SEG_DAYS;
        SData/*13:0*/ FrenchRepublicanCalendarAlarmClock__DOT__SEG_WEEKS;
        SData/*13:0*/ FrenchRepublicanCalendarAlarmClock__DOT__SEG_MONTHS;
        SData/*13:0*/ FrenchRepublicanCalendarAlarmClock__DOT__SEG_YEARS;
        SData/*13:0*/ FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i20__DOT__out;
        SData/*13:0*/ FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i21__DOT__out;
        SData/*13:0*/ FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i25__DOT__out;
        SData/*13:0*/ FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i26__DOT__out;
        SData/*13:0*/ FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i27__DOT__out;
        SData/*13:0*/ FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i28__DOT__out;
        SData/*13:0*/ FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i29__DOT__out;
        IData/*31:0*/ __VactIterCount;
        VlUnpacked<SData/*13:0*/, 128> FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i20__DOT__my_lut;
        VlUnpacked<SData/*13:0*/, 128> FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i21__DOT__my_lut;
        VlUnpacked<SData/*13:0*/, 128> FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i25__DOT__my_lut;
        VlUnpacked<SData/*13:0*/, 128> FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i26__DOT__my_lut;
        VlUnpacked<SData/*13:0*/, 128> FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i27__DOT__my_lut;
        VlUnpacked<SData/*13:0*/, 128> FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i28__DOT__my_lut;
        VlUnpacked<SData/*13:0*/, 128> FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i29__DOT__my_lut;
    };
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<1> __VicoTriggered;
    VlTriggerVec<12> __VactTriggered;
    VlTriggerVec<12> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vtop__Syms* const vlSymsp;

    // PARAMETERS
    static constexpr IData/*31:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i0__DOT__Bits = 7U;
    static constexpr IData/*31:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i1__DOT__Bits = 7U;
    static constexpr IData/*31:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i2__DOT__Bits = 4U;
    static constexpr IData/*31:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i3__DOT__Bits = 4U;
    static constexpr IData/*31:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i4__DOT__Bits = 2U;
    static constexpr IData/*31:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i5__DOT__Bits = 4U;
    static constexpr IData/*31:0*/ FrenchRepublicanCalendarAlarmClock__DOT__Mux_2x1_NBits_i6__DOT__Bits = 7U;
    static constexpr IData/*31:0*/ FrenchRepublicanCalendarAlarmClock__DOT__Mux_2x1_NBits_i7__DOT__Bits = 4U;
    static constexpr IData/*31:0*/ FrenchRepublicanCalendarAlarmClock__DOT__Mux_2x1_NBits_i8__DOT__Bits = 4U;
    static constexpr IData/*31:0*/ FrenchRepublicanCalendarAlarmClock__DOT__Mux_2x1_NBits_i9__DOT__Bits = 2U;
    static constexpr IData/*31:0*/ FrenchRepublicanCalendarAlarmClock__DOT__Mux_2x1_NBits_i10__DOT__Bits = 4U;
    static constexpr IData/*31:0*/ FrenchRepublicanCalendarAlarmClock__DOT__Mux_2x1_NBits_i11__DOT__Bits = 7U;
    static constexpr IData/*31:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i12__DOT__Bits = 7U;
    static constexpr IData/*31:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i13__DOT__Bits = 4U;
    static constexpr IData/*31:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i14__DOT__Bits = 4U;
    static constexpr IData/*31:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i15__DOT__Bits = 2U;
    static constexpr IData/*31:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i16__DOT__Bits = 4U;
    static constexpr IData/*31:0*/ FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i17__DOT__Bits = 4U;
    static constexpr IData/*31:0*/ FrenchRepublicanCalendarAlarmClock__DOT__CompUnsigned_i18__DOT__Bits = 7U;
    static constexpr IData/*31:0*/ FrenchRepublicanCalendarAlarmClock__DOT__CompUnsigned_i19__DOT__Bits = 4U;
    static constexpr IData/*31:0*/ FrenchRepublicanCalendarAlarmClock__DOT__CompUnsigned_i22__DOT__Bits = 4U;
    static constexpr IData/*31:0*/ FrenchRepublicanCalendarAlarmClock__DOT__CompUnsigned_i23__DOT__Bits = 2U;
    static constexpr IData/*31:0*/ FrenchRepublicanCalendarAlarmClock__DOT__CompUnsigned_i24__DOT__Bits = 4U;

    // CONSTRUCTORS
    Vtop___024root(Vtop__Syms* symsp, const char* v__name);
    ~Vtop___024root();
    VL_UNCOPYABLE(Vtop___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
