// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Symbol table implementation internals

#include "Vtop__pch.h"
#include "Vtop.h"
#include "Vtop___024root.h"

// FUNCTIONS
Vtop__Syms::~Vtop__Syms()
{

    // Tear down scope hierarchy
    __Vhier.remove(0, &__Vscope_FrenchRepublicanCalendarAlarmClock);
    __Vhier.remove(&__Vscope_FrenchRepublicanCalendarAlarmClock, &__Vscope_FrenchRepublicanCalendarAlarmClock__CompUnsigned_i18);
    __Vhier.remove(&__Vscope_FrenchRepublicanCalendarAlarmClock, &__Vscope_FrenchRepublicanCalendarAlarmClock__CompUnsigned_i19);
    __Vhier.remove(&__Vscope_FrenchRepublicanCalendarAlarmClock, &__Vscope_FrenchRepublicanCalendarAlarmClock__CompUnsigned_i22);
    __Vhier.remove(&__Vscope_FrenchRepublicanCalendarAlarmClock, &__Vscope_FrenchRepublicanCalendarAlarmClock__CompUnsigned_i23);
    __Vhier.remove(&__Vscope_FrenchRepublicanCalendarAlarmClock, &__Vscope_FrenchRepublicanCalendarAlarmClock__CompUnsigned_i24);
    __Vhier.remove(&__Vscope_FrenchRepublicanCalendarAlarmClock, &__Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i0);
    __Vhier.remove(&__Vscope_FrenchRepublicanCalendarAlarmClock, &__Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i1);
    __Vhier.remove(&__Vscope_FrenchRepublicanCalendarAlarmClock, &__Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i12);
    __Vhier.remove(&__Vscope_FrenchRepublicanCalendarAlarmClock, &__Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i13);
    __Vhier.remove(&__Vscope_FrenchRepublicanCalendarAlarmClock, &__Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i14);
    __Vhier.remove(&__Vscope_FrenchRepublicanCalendarAlarmClock, &__Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i15);
    __Vhier.remove(&__Vscope_FrenchRepublicanCalendarAlarmClock, &__Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i16);
    __Vhier.remove(&__Vscope_FrenchRepublicanCalendarAlarmClock, &__Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i17);
    __Vhier.remove(&__Vscope_FrenchRepublicanCalendarAlarmClock, &__Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i2);
    __Vhier.remove(&__Vscope_FrenchRepublicanCalendarAlarmClock, &__Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i3);
    __Vhier.remove(&__Vscope_FrenchRepublicanCalendarAlarmClock, &__Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i4);
    __Vhier.remove(&__Vscope_FrenchRepublicanCalendarAlarmClock, &__Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i5);
    __Vhier.remove(&__Vscope_FrenchRepublicanCalendarAlarmClock, &__Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i20);
    __Vhier.remove(&__Vscope_FrenchRepublicanCalendarAlarmClock, &__Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i21);
    __Vhier.remove(&__Vscope_FrenchRepublicanCalendarAlarmClock, &__Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i25);
    __Vhier.remove(&__Vscope_FrenchRepublicanCalendarAlarmClock, &__Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i26);
    __Vhier.remove(&__Vscope_FrenchRepublicanCalendarAlarmClock, &__Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i27);
    __Vhier.remove(&__Vscope_FrenchRepublicanCalendarAlarmClock, &__Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i28);
    __Vhier.remove(&__Vscope_FrenchRepublicanCalendarAlarmClock, &__Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i29);
    __Vhier.remove(&__Vscope_FrenchRepublicanCalendarAlarmClock, &__Vscope_FrenchRepublicanCalendarAlarmClock__Mux_2x1_NBits_i10);
    __Vhier.remove(&__Vscope_FrenchRepublicanCalendarAlarmClock, &__Vscope_FrenchRepublicanCalendarAlarmClock__Mux_2x1_NBits_i11);
    __Vhier.remove(&__Vscope_FrenchRepublicanCalendarAlarmClock, &__Vscope_FrenchRepublicanCalendarAlarmClock__Mux_2x1_NBits_i6);
    __Vhier.remove(&__Vscope_FrenchRepublicanCalendarAlarmClock, &__Vscope_FrenchRepublicanCalendarAlarmClock__Mux_2x1_NBits_i7);
    __Vhier.remove(&__Vscope_FrenchRepublicanCalendarAlarmClock, &__Vscope_FrenchRepublicanCalendarAlarmClock__Mux_2x1_NBits_i8);
    __Vhier.remove(&__Vscope_FrenchRepublicanCalendarAlarmClock, &__Vscope_FrenchRepublicanCalendarAlarmClock__Mux_2x1_NBits_i9);

}

Vtop__Syms::Vtop__Syms(VerilatedContext* contextp, const char* namep, Vtop* modelp)
    : VerilatedSyms{contextp}
    // Setup internal state of the Syms class
    , __Vm_modelp{modelp}
    // Setup module instances
    , TOP{this, namep}
{
        // Check resources
        Verilated::stackCheck(27);
    // Configure time unit / time precision
    _vm_contextp__->timeunit(-12);
    _vm_contextp__->timeprecision(-12);
    // Setup each module's pointers to their submodules
    // Setup each module's pointer back to symbol table (for public functions)
    TOP.__Vconfigure(true);
    // Setup scopes
    __Vscope_FrenchRepublicanCalendarAlarmClock.configure(this, name(), "FrenchRepublicanCalendarAlarmClock", "FrenchRepublicanCalendarAlarmClock", -12, VerilatedScope::SCOPE_MODULE);
    __Vscope_FrenchRepublicanCalendarAlarmClock__CompUnsigned_i18.configure(this, name(), "FrenchRepublicanCalendarAlarmClock.CompUnsigned_i18", "CompUnsigned_i18", -12, VerilatedScope::SCOPE_MODULE);
    __Vscope_FrenchRepublicanCalendarAlarmClock__CompUnsigned_i19.configure(this, name(), "FrenchRepublicanCalendarAlarmClock.CompUnsigned_i19", "CompUnsigned_i19", -12, VerilatedScope::SCOPE_MODULE);
    __Vscope_FrenchRepublicanCalendarAlarmClock__CompUnsigned_i22.configure(this, name(), "FrenchRepublicanCalendarAlarmClock.CompUnsigned_i22", "CompUnsigned_i22", -12, VerilatedScope::SCOPE_MODULE);
    __Vscope_FrenchRepublicanCalendarAlarmClock__CompUnsigned_i23.configure(this, name(), "FrenchRepublicanCalendarAlarmClock.CompUnsigned_i23", "CompUnsigned_i23", -12, VerilatedScope::SCOPE_MODULE);
    __Vscope_FrenchRepublicanCalendarAlarmClock__CompUnsigned_i24.configure(this, name(), "FrenchRepublicanCalendarAlarmClock.CompUnsigned_i24", "CompUnsigned_i24", -12, VerilatedScope::SCOPE_MODULE);
    __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i0.configure(this, name(), "FrenchRepublicanCalendarAlarmClock.DIG_Counter_Nbit_i0", "DIG_Counter_Nbit_i0", -12, VerilatedScope::SCOPE_MODULE);
    __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i1.configure(this, name(), "FrenchRepublicanCalendarAlarmClock.DIG_Counter_Nbit_i1", "DIG_Counter_Nbit_i1", -12, VerilatedScope::SCOPE_MODULE);
    __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i12.configure(this, name(), "FrenchRepublicanCalendarAlarmClock.DIG_Counter_Nbit_i12", "DIG_Counter_Nbit_i12", -12, VerilatedScope::SCOPE_MODULE);
    __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i13.configure(this, name(), "FrenchRepublicanCalendarAlarmClock.DIG_Counter_Nbit_i13", "DIG_Counter_Nbit_i13", -12, VerilatedScope::SCOPE_MODULE);
    __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i14.configure(this, name(), "FrenchRepublicanCalendarAlarmClock.DIG_Counter_Nbit_i14", "DIG_Counter_Nbit_i14", -12, VerilatedScope::SCOPE_MODULE);
    __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i15.configure(this, name(), "FrenchRepublicanCalendarAlarmClock.DIG_Counter_Nbit_i15", "DIG_Counter_Nbit_i15", -12, VerilatedScope::SCOPE_MODULE);
    __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i16.configure(this, name(), "FrenchRepublicanCalendarAlarmClock.DIG_Counter_Nbit_i16", "DIG_Counter_Nbit_i16", -12, VerilatedScope::SCOPE_MODULE);
    __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i17.configure(this, name(), "FrenchRepublicanCalendarAlarmClock.DIG_Counter_Nbit_i17", "DIG_Counter_Nbit_i17", -12, VerilatedScope::SCOPE_MODULE);
    __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i2.configure(this, name(), "FrenchRepublicanCalendarAlarmClock.DIG_Counter_Nbit_i2", "DIG_Counter_Nbit_i2", -12, VerilatedScope::SCOPE_MODULE);
    __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i3.configure(this, name(), "FrenchRepublicanCalendarAlarmClock.DIG_Counter_Nbit_i3", "DIG_Counter_Nbit_i3", -12, VerilatedScope::SCOPE_MODULE);
    __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i4.configure(this, name(), "FrenchRepublicanCalendarAlarmClock.DIG_Counter_Nbit_i4", "DIG_Counter_Nbit_i4", -12, VerilatedScope::SCOPE_MODULE);
    __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i5.configure(this, name(), "FrenchRepublicanCalendarAlarmClock.DIG_Counter_Nbit_i5", "DIG_Counter_Nbit_i5", -12, VerilatedScope::SCOPE_MODULE);
    __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i20.configure(this, name(), "FrenchRepublicanCalendarAlarmClock.LUT_SEG_DECODER_i20", "LUT_SEG_DECODER_i20", -12, VerilatedScope::SCOPE_MODULE);
    __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i21.configure(this, name(), "FrenchRepublicanCalendarAlarmClock.LUT_SEG_DECODER_i21", "LUT_SEG_DECODER_i21", -12, VerilatedScope::SCOPE_MODULE);
    __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i25.configure(this, name(), "FrenchRepublicanCalendarAlarmClock.LUT_SEG_DECODER_i25", "LUT_SEG_DECODER_i25", -12, VerilatedScope::SCOPE_MODULE);
    __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i26.configure(this, name(), "FrenchRepublicanCalendarAlarmClock.LUT_SEG_DECODER_i26", "LUT_SEG_DECODER_i26", -12, VerilatedScope::SCOPE_MODULE);
    __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i27.configure(this, name(), "FrenchRepublicanCalendarAlarmClock.LUT_SEG_DECODER_i27", "LUT_SEG_DECODER_i27", -12, VerilatedScope::SCOPE_MODULE);
    __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i28.configure(this, name(), "FrenchRepublicanCalendarAlarmClock.LUT_SEG_DECODER_i28", "LUT_SEG_DECODER_i28", -12, VerilatedScope::SCOPE_MODULE);
    __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i29.configure(this, name(), "FrenchRepublicanCalendarAlarmClock.LUT_SEG_DECODER_i29", "LUT_SEG_DECODER_i29", -12, VerilatedScope::SCOPE_MODULE);
    __Vscope_FrenchRepublicanCalendarAlarmClock__Mux_2x1_NBits_i10.configure(this, name(), "FrenchRepublicanCalendarAlarmClock.Mux_2x1_NBits_i10", "Mux_2x1_NBits_i10", -12, VerilatedScope::SCOPE_MODULE);
    __Vscope_FrenchRepublicanCalendarAlarmClock__Mux_2x1_NBits_i11.configure(this, name(), "FrenchRepublicanCalendarAlarmClock.Mux_2x1_NBits_i11", "Mux_2x1_NBits_i11", -12, VerilatedScope::SCOPE_MODULE);
    __Vscope_FrenchRepublicanCalendarAlarmClock__Mux_2x1_NBits_i6.configure(this, name(), "FrenchRepublicanCalendarAlarmClock.Mux_2x1_NBits_i6", "Mux_2x1_NBits_i6", -12, VerilatedScope::SCOPE_MODULE);
    __Vscope_FrenchRepublicanCalendarAlarmClock__Mux_2x1_NBits_i7.configure(this, name(), "FrenchRepublicanCalendarAlarmClock.Mux_2x1_NBits_i7", "Mux_2x1_NBits_i7", -12, VerilatedScope::SCOPE_MODULE);
    __Vscope_FrenchRepublicanCalendarAlarmClock__Mux_2x1_NBits_i8.configure(this, name(), "FrenchRepublicanCalendarAlarmClock.Mux_2x1_NBits_i8", "Mux_2x1_NBits_i8", -12, VerilatedScope::SCOPE_MODULE);
    __Vscope_FrenchRepublicanCalendarAlarmClock__Mux_2x1_NBits_i9.configure(this, name(), "FrenchRepublicanCalendarAlarmClock.Mux_2x1_NBits_i9", "Mux_2x1_NBits_i9", -12, VerilatedScope::SCOPE_MODULE);
    __Vscope_TOP.configure(this, name(), "TOP", "TOP", 0, VerilatedScope::SCOPE_OTHER);

    // Set up scope hierarchy
    __Vhier.add(0, &__Vscope_FrenchRepublicanCalendarAlarmClock);
    __Vhier.add(&__Vscope_FrenchRepublicanCalendarAlarmClock, &__Vscope_FrenchRepublicanCalendarAlarmClock__CompUnsigned_i18);
    __Vhier.add(&__Vscope_FrenchRepublicanCalendarAlarmClock, &__Vscope_FrenchRepublicanCalendarAlarmClock__CompUnsigned_i19);
    __Vhier.add(&__Vscope_FrenchRepublicanCalendarAlarmClock, &__Vscope_FrenchRepublicanCalendarAlarmClock__CompUnsigned_i22);
    __Vhier.add(&__Vscope_FrenchRepublicanCalendarAlarmClock, &__Vscope_FrenchRepublicanCalendarAlarmClock__CompUnsigned_i23);
    __Vhier.add(&__Vscope_FrenchRepublicanCalendarAlarmClock, &__Vscope_FrenchRepublicanCalendarAlarmClock__CompUnsigned_i24);
    __Vhier.add(&__Vscope_FrenchRepublicanCalendarAlarmClock, &__Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i0);
    __Vhier.add(&__Vscope_FrenchRepublicanCalendarAlarmClock, &__Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i1);
    __Vhier.add(&__Vscope_FrenchRepublicanCalendarAlarmClock, &__Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i12);
    __Vhier.add(&__Vscope_FrenchRepublicanCalendarAlarmClock, &__Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i13);
    __Vhier.add(&__Vscope_FrenchRepublicanCalendarAlarmClock, &__Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i14);
    __Vhier.add(&__Vscope_FrenchRepublicanCalendarAlarmClock, &__Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i15);
    __Vhier.add(&__Vscope_FrenchRepublicanCalendarAlarmClock, &__Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i16);
    __Vhier.add(&__Vscope_FrenchRepublicanCalendarAlarmClock, &__Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i17);
    __Vhier.add(&__Vscope_FrenchRepublicanCalendarAlarmClock, &__Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i2);
    __Vhier.add(&__Vscope_FrenchRepublicanCalendarAlarmClock, &__Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i3);
    __Vhier.add(&__Vscope_FrenchRepublicanCalendarAlarmClock, &__Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i4);
    __Vhier.add(&__Vscope_FrenchRepublicanCalendarAlarmClock, &__Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i5);
    __Vhier.add(&__Vscope_FrenchRepublicanCalendarAlarmClock, &__Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i20);
    __Vhier.add(&__Vscope_FrenchRepublicanCalendarAlarmClock, &__Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i21);
    __Vhier.add(&__Vscope_FrenchRepublicanCalendarAlarmClock, &__Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i25);
    __Vhier.add(&__Vscope_FrenchRepublicanCalendarAlarmClock, &__Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i26);
    __Vhier.add(&__Vscope_FrenchRepublicanCalendarAlarmClock, &__Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i27);
    __Vhier.add(&__Vscope_FrenchRepublicanCalendarAlarmClock, &__Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i28);
    __Vhier.add(&__Vscope_FrenchRepublicanCalendarAlarmClock, &__Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i29);
    __Vhier.add(&__Vscope_FrenchRepublicanCalendarAlarmClock, &__Vscope_FrenchRepublicanCalendarAlarmClock__Mux_2x1_NBits_i10);
    __Vhier.add(&__Vscope_FrenchRepublicanCalendarAlarmClock, &__Vscope_FrenchRepublicanCalendarAlarmClock__Mux_2x1_NBits_i11);
    __Vhier.add(&__Vscope_FrenchRepublicanCalendarAlarmClock, &__Vscope_FrenchRepublicanCalendarAlarmClock__Mux_2x1_NBits_i6);
    __Vhier.add(&__Vscope_FrenchRepublicanCalendarAlarmClock, &__Vscope_FrenchRepublicanCalendarAlarmClock__Mux_2x1_NBits_i7);
    __Vhier.add(&__Vscope_FrenchRepublicanCalendarAlarmClock, &__Vscope_FrenchRepublicanCalendarAlarmClock__Mux_2x1_NBits_i8);
    __Vhier.add(&__Vscope_FrenchRepublicanCalendarAlarmClock, &__Vscope_FrenchRepublicanCalendarAlarmClock__Mux_2x1_NBits_i9);

    // Setup export functions
    for (int __Vfinal = 0; __Vfinal < 2; ++__Vfinal) {
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"ALARM_DAYS", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__ALARM_DAYS), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"ALARM_DAYS_temp", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__ALARM_DAYS_temp), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"ALARM_EN", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__ALARM_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"ALARM_HOURS", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__ALARM_HOURS), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"ALARM_HOURS_temp", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__ALARM_HOURS_temp), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"ALARM_MINUTES", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__ALARM_MINUTES), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,6,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"ALARM_MINUTES_temp", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__ALARM_MINUTES_temp), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,6,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"ALARM_MONTHS", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__ALARM_MONTHS), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"ALARM_MONTHS_temp", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__ALARM_MONTHS_temp), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"ALARM_WEEKS", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__ALARM_WEEKS), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"ALARM_WEEKS_temp", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__ALARM_WEEKS_temp), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"BUZZ", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__BUZZ), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"CLK", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__CLK), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"CLR", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__CLR), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"DAYS", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DAYS), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"DAYS_temp", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DAYS_temp), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"DAY_ADV", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DAY_ADV), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"HOURS", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__HOURS), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"HOURS_temp", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__HOURS_temp), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"HR_ADV", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__HR_ADV), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"MINUTES", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__MINUTES), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,6,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"MINUTES_temp", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__MINUTES_temp), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,6,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"MIN_ADV", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__MIN_ADV), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"MONTHS", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__MONTHS), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"MONTHS_temp", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__MONTHS_temp), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"MONTH_ADV", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__MONTH_ADV), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"SECONDS", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__SECONDS), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,6,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"SECONDS_temp", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__SECONDS_temp), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,6,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"SEG_DAYS", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__SEG_DAYS), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,13,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"SEG_HOURS", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__SEG_HOURS), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,13,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"SEG_MINUTES", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__SEG_MINUTES), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,13,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"SEG_MONTHS", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__SEG_MONTHS), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,13,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"SEG_SECONDS", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__SEG_SECONDS), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,13,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"SEG_WEEKS", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__SEG_WEEKS), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,13,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"SEG_YEARS", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__SEG_YEARS), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,13,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"SETUP_ALARM", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__SETUP_ALARM), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"SETUP_TIME", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__SETUP_TIME), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"WEEKS", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__WEEKS), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"WEEKS_temp", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__WEEKS_temp), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"WEEK_ADV", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__WEEK_ADV), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"YEARS", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__YEARS), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"YEARS_temp", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__YEARS_temp), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"YEAR_ADV", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__YEAR_ADV), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s0", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s0), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s1", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s10", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s10), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s11", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s11), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s12", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s12), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s13", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s13), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s14", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s14), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s15", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s15), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s16", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s16), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s17", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s17), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s18", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s18), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s19", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s19), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s2", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s20", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s20), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s21", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s21), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s22", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s22), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s23", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s23), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s24", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s24), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s25", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s25), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s26", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s26), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,6,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s27", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s27), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s28", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s28), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s29", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s29), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s3", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s3), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s30", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s30), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s31", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s31), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s32", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s32), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s33", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s33), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s34", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s34), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,6,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s35", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s35), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s36", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s36), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s37", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s37), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s38", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s38), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s39", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s39), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s4", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s4), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s40", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s40), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s41", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s41), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s42", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s42), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,6,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s43", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s43), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s44", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s44), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s45", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s45), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s46", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s46), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s47", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s47), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s48", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s48), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s49", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s49), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s5", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s5), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s50", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s50), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s51", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s51), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s52", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s52), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s53", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s53), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s54", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s54), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,6,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s55", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s55), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s56", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s56), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s57", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s57), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s58", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s58), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s59", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s59), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s6", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s6), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s60", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s60), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s61", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s61), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s62", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s62), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s63", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s63), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s64", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s64), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s65", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s65), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s66", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s66), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,6,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s67", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s67), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s68", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s68), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s69", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s69), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s7", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s7), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s70", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s70), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s71", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s71), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s72", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s72), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s73", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s73), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s74", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s74), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s75", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s75), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s76", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s76), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s77", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s77), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s78", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s78), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,6,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s79", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s79), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s8", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s8), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s80", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s80), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s81", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s81), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s82", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s82), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s83", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s83), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s84", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s84), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s85", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s85), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s86", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s86), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s87", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s87), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s88", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s88), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s89", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s89), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s9", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s9), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s90", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s90), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s91", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s91), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s92", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s92), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s93", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s93), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s94", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s94), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s95", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s95), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s96", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s96), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s97", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s97), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s98", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s98), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,6,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock.varInsert(__Vfinal,"s99", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__s99), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,6,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__CompUnsigned_i18.varInsert(__Vfinal,"Bits", const_cast<void*>(static_cast<const void*>(&(TOP.FrenchRepublicanCalendarAlarmClock__DOT__CompUnsigned_i18__DOT__Bits))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__CompUnsigned_i18.varInsert(__Vfinal,"\\< ", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__CompUnsigned_i18__DOT____03c), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__CompUnsigned_i18.varInsert(__Vfinal,"\\= ", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__CompUnsigned_i18__DOT____03d), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__CompUnsigned_i18.varInsert(__Vfinal,"\\> ", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__CompUnsigned_i18__DOT____03e), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__CompUnsigned_i18.varInsert(__Vfinal,"a", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__CompUnsigned_i18__DOT__a), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,6,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__CompUnsigned_i18.varInsert(__Vfinal,"b", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__CompUnsigned_i18__DOT__b), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,6,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__CompUnsigned_i19.varInsert(__Vfinal,"Bits", const_cast<void*>(static_cast<const void*>(&(TOP.FrenchRepublicanCalendarAlarmClock__DOT__CompUnsigned_i19__DOT__Bits))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__CompUnsigned_i19.varInsert(__Vfinal,"\\< ", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__CompUnsigned_i19__DOT____03c), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__CompUnsigned_i19.varInsert(__Vfinal,"\\= ", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__CompUnsigned_i19__DOT____03d), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__CompUnsigned_i19.varInsert(__Vfinal,"\\> ", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__CompUnsigned_i19__DOT____03e), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__CompUnsigned_i19.varInsert(__Vfinal,"a", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__CompUnsigned_i19__DOT__a), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__CompUnsigned_i19.varInsert(__Vfinal,"b", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__CompUnsigned_i19__DOT__b), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__CompUnsigned_i22.varInsert(__Vfinal,"Bits", const_cast<void*>(static_cast<const void*>(&(TOP.FrenchRepublicanCalendarAlarmClock__DOT__CompUnsigned_i22__DOT__Bits))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__CompUnsigned_i22.varInsert(__Vfinal,"\\< ", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__CompUnsigned_i22__DOT____03c), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__CompUnsigned_i22.varInsert(__Vfinal,"\\= ", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__CompUnsigned_i22__DOT____03d), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__CompUnsigned_i22.varInsert(__Vfinal,"\\> ", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__CompUnsigned_i22__DOT____03e), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__CompUnsigned_i22.varInsert(__Vfinal,"a", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__CompUnsigned_i22__DOT__a), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__CompUnsigned_i22.varInsert(__Vfinal,"b", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__CompUnsigned_i22__DOT__b), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__CompUnsigned_i23.varInsert(__Vfinal,"Bits", const_cast<void*>(static_cast<const void*>(&(TOP.FrenchRepublicanCalendarAlarmClock__DOT__CompUnsigned_i23__DOT__Bits))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__CompUnsigned_i23.varInsert(__Vfinal,"\\< ", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__CompUnsigned_i23__DOT____03c), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__CompUnsigned_i23.varInsert(__Vfinal,"\\= ", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__CompUnsigned_i23__DOT____03d), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__CompUnsigned_i23.varInsert(__Vfinal,"\\> ", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__CompUnsigned_i23__DOT____03e), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__CompUnsigned_i23.varInsert(__Vfinal,"a", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__CompUnsigned_i23__DOT__a), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__CompUnsigned_i23.varInsert(__Vfinal,"b", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__CompUnsigned_i23__DOT__b), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__CompUnsigned_i24.varInsert(__Vfinal,"Bits", const_cast<void*>(static_cast<const void*>(&(TOP.FrenchRepublicanCalendarAlarmClock__DOT__CompUnsigned_i24__DOT__Bits))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__CompUnsigned_i24.varInsert(__Vfinal,"\\< ", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__CompUnsigned_i24__DOT____03c), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__CompUnsigned_i24.varInsert(__Vfinal,"\\= ", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__CompUnsigned_i24__DOT____03d), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__CompUnsigned_i24.varInsert(__Vfinal,"\\> ", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__CompUnsigned_i24__DOT____03e), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__CompUnsigned_i24.varInsert(__Vfinal,"a", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__CompUnsigned_i24__DOT__a), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__CompUnsigned_i24.varInsert(__Vfinal,"b", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__CompUnsigned_i24__DOT__b), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i0.varInsert(__Vfinal,"Bits", const_cast<void*>(static_cast<const void*>(&(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i0__DOT__Bits))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i0.varInsert(__Vfinal,"C", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i0__DOT__C), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i0.varInsert(__Vfinal,"clr", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i0__DOT__clr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i0.varInsert(__Vfinal,"count", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i0__DOT__count), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,6,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i0.varInsert(__Vfinal,"en", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i0__DOT__en), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i0.varInsert(__Vfinal,"out", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i0__DOT__out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,6,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i0.varInsert(__Vfinal,"ovf", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i0__DOT__ovf), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i1.varInsert(__Vfinal,"Bits", const_cast<void*>(static_cast<const void*>(&(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i1__DOT__Bits))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i1.varInsert(__Vfinal,"C", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i1__DOT__C), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i1.varInsert(__Vfinal,"clr", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i1__DOT__clr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i1.varInsert(__Vfinal,"count", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i1__DOT__count), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,6,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i1.varInsert(__Vfinal,"en", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i1__DOT__en), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i1.varInsert(__Vfinal,"out", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i1__DOT__out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,6,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i1.varInsert(__Vfinal,"ovf", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i1__DOT__ovf), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i12.varInsert(__Vfinal,"Bits", const_cast<void*>(static_cast<const void*>(&(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i12__DOT__Bits))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i12.varInsert(__Vfinal,"C", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i12__DOT__C), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i12.varInsert(__Vfinal,"clr", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i12__DOT__clr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i12.varInsert(__Vfinal,"count", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i12__DOT__count), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,6,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i12.varInsert(__Vfinal,"en", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i12__DOT__en), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i12.varInsert(__Vfinal,"out", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i12__DOT__out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,6,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i12.varInsert(__Vfinal,"ovf", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i12__DOT__ovf), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i13.varInsert(__Vfinal,"Bits", const_cast<void*>(static_cast<const void*>(&(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i13__DOT__Bits))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i13.varInsert(__Vfinal,"C", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i13__DOT__C), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i13.varInsert(__Vfinal,"clr", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i13__DOT__clr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i13.varInsert(__Vfinal,"count", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i13__DOT__count), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i13.varInsert(__Vfinal,"en", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i13__DOT__en), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i13.varInsert(__Vfinal,"out", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i13__DOT__out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i13.varInsert(__Vfinal,"ovf", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i13__DOT__ovf), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i14.varInsert(__Vfinal,"Bits", const_cast<void*>(static_cast<const void*>(&(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i14__DOT__Bits))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i14.varInsert(__Vfinal,"C", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i14__DOT__C), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i14.varInsert(__Vfinal,"clr", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i14__DOT__clr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i14.varInsert(__Vfinal,"count", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i14__DOT__count), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i14.varInsert(__Vfinal,"en", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i14__DOT__en), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i14.varInsert(__Vfinal,"out", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i14__DOT__out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i14.varInsert(__Vfinal,"ovf", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i14__DOT__ovf), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i15.varInsert(__Vfinal,"Bits", const_cast<void*>(static_cast<const void*>(&(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i15__DOT__Bits))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i15.varInsert(__Vfinal,"C", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i15__DOT__C), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i15.varInsert(__Vfinal,"clr", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i15__DOT__clr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i15.varInsert(__Vfinal,"count", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i15__DOT__count), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i15.varInsert(__Vfinal,"en", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i15__DOT__en), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i15.varInsert(__Vfinal,"out", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i15__DOT__out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i15.varInsert(__Vfinal,"ovf", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i15__DOT__ovf), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i16.varInsert(__Vfinal,"Bits", const_cast<void*>(static_cast<const void*>(&(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i16__DOT__Bits))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i16.varInsert(__Vfinal,"C", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i16__DOT__C), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i16.varInsert(__Vfinal,"clr", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i16__DOT__clr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i16.varInsert(__Vfinal,"count", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i16__DOT__count), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i16.varInsert(__Vfinal,"en", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i16__DOT__en), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i16.varInsert(__Vfinal,"out", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i16__DOT__out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i16.varInsert(__Vfinal,"ovf", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i16__DOT__ovf), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i17.varInsert(__Vfinal,"Bits", const_cast<void*>(static_cast<const void*>(&(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i17__DOT__Bits))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i17.varInsert(__Vfinal,"C", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i17__DOT__C), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i17.varInsert(__Vfinal,"clr", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i17__DOT__clr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i17.varInsert(__Vfinal,"count", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i17__DOT__count), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i17.varInsert(__Vfinal,"en", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i17__DOT__en), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i17.varInsert(__Vfinal,"out", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i17__DOT__out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i17.varInsert(__Vfinal,"ovf", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i17__DOT__ovf), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i2.varInsert(__Vfinal,"Bits", const_cast<void*>(static_cast<const void*>(&(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i2__DOT__Bits))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i2.varInsert(__Vfinal,"C", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i2__DOT__C), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i2.varInsert(__Vfinal,"clr", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i2__DOT__clr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i2.varInsert(__Vfinal,"count", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i2__DOT__count), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i2.varInsert(__Vfinal,"en", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i2__DOT__en), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i2.varInsert(__Vfinal,"out", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i2__DOT__out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i2.varInsert(__Vfinal,"ovf", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i2__DOT__ovf), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i3.varInsert(__Vfinal,"Bits", const_cast<void*>(static_cast<const void*>(&(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i3__DOT__Bits))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i3.varInsert(__Vfinal,"C", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i3__DOT__C), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i3.varInsert(__Vfinal,"clr", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i3__DOT__clr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i3.varInsert(__Vfinal,"count", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i3__DOT__count), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i3.varInsert(__Vfinal,"en", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i3__DOT__en), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i3.varInsert(__Vfinal,"out", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i3__DOT__out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i3.varInsert(__Vfinal,"ovf", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i3__DOT__ovf), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i4.varInsert(__Vfinal,"Bits", const_cast<void*>(static_cast<const void*>(&(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i4__DOT__Bits))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i4.varInsert(__Vfinal,"C", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i4__DOT__C), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i4.varInsert(__Vfinal,"clr", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i4__DOT__clr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i4.varInsert(__Vfinal,"count", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i4__DOT__count), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i4.varInsert(__Vfinal,"en", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i4__DOT__en), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i4.varInsert(__Vfinal,"out", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i4__DOT__out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i4.varInsert(__Vfinal,"ovf", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i4__DOT__ovf), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i5.varInsert(__Vfinal,"Bits", const_cast<void*>(static_cast<const void*>(&(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i5__DOT__Bits))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i5.varInsert(__Vfinal,"C", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i5__DOT__C), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i5.varInsert(__Vfinal,"clr", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i5__DOT__clr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i5.varInsert(__Vfinal,"count", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i5__DOT__count), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i5.varInsert(__Vfinal,"en", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i5__DOT__en), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i5.varInsert(__Vfinal,"out", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i5__DOT__out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__DIG_Counter_Nbit_i5.varInsert(__Vfinal,"ovf", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i5__DOT__ovf), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i20.varInsert(__Vfinal,"\\0 ", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i20__DOT____030), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i20.varInsert(__Vfinal,"\\1 ", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i20__DOT____031), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i20.varInsert(__Vfinal,"\\2 ", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i20__DOT____032), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i20.varInsert(__Vfinal,"\\3 ", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i20__DOT____033), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i20.varInsert(__Vfinal,"\\4 ", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i20__DOT____034), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i20.varInsert(__Vfinal,"\\5 ", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i20__DOT____035), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i20.varInsert(__Vfinal,"\\6 ", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i20__DOT____036), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i20.varInsert(__Vfinal,"my_lut", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i20__DOT__my_lut), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,2 ,13,0 ,0,127);
        __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i20.varInsert(__Vfinal,"out", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i20__DOT__out), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,13,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i20.varInsert(__Vfinal,"temp", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i20__DOT__temp), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,6,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i21.varInsert(__Vfinal,"\\0 ", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i21__DOT____030), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i21.varInsert(__Vfinal,"\\1 ", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i21__DOT____031), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i21.varInsert(__Vfinal,"\\2 ", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i21__DOT____032), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i21.varInsert(__Vfinal,"\\3 ", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i21__DOT____033), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i21.varInsert(__Vfinal,"\\4 ", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i21__DOT____034), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i21.varInsert(__Vfinal,"\\5 ", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i21__DOT____035), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i21.varInsert(__Vfinal,"\\6 ", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i21__DOT____036), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i21.varInsert(__Vfinal,"my_lut", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i21__DOT__my_lut), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,2 ,13,0 ,0,127);
        __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i21.varInsert(__Vfinal,"out", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i21__DOT__out), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,13,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i21.varInsert(__Vfinal,"temp", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i21__DOT__temp), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,6,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i25.varInsert(__Vfinal,"\\0 ", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i25__DOT____030), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i25.varInsert(__Vfinal,"\\1 ", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i25__DOT____031), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i25.varInsert(__Vfinal,"\\2 ", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i25__DOT____032), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i25.varInsert(__Vfinal,"\\3 ", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i25__DOT____033), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i25.varInsert(__Vfinal,"\\4 ", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i25__DOT____034), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i25.varInsert(__Vfinal,"\\5 ", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i25__DOT____035), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i25.varInsert(__Vfinal,"\\6 ", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i25__DOT____036), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i25.varInsert(__Vfinal,"my_lut", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i25__DOT__my_lut), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,2 ,13,0 ,0,127);
        __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i25.varInsert(__Vfinal,"out", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i25__DOT__out), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,13,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i25.varInsert(__Vfinal,"temp", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i25__DOT__temp), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,6,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i26.varInsert(__Vfinal,"\\0 ", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i26__DOT____030), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i26.varInsert(__Vfinal,"\\1 ", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i26__DOT____031), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i26.varInsert(__Vfinal,"\\2 ", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i26__DOT____032), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i26.varInsert(__Vfinal,"\\3 ", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i26__DOT____033), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i26.varInsert(__Vfinal,"\\4 ", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i26__DOT____034), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i26.varInsert(__Vfinal,"\\5 ", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i26__DOT____035), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i26.varInsert(__Vfinal,"\\6 ", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i26__DOT____036), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i26.varInsert(__Vfinal,"my_lut", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i26__DOT__my_lut), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,2 ,13,0 ,0,127);
        __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i26.varInsert(__Vfinal,"out", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i26__DOT__out), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,13,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i26.varInsert(__Vfinal,"temp", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i26__DOT__temp), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,6,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i27.varInsert(__Vfinal,"\\0 ", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i27__DOT____030), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i27.varInsert(__Vfinal,"\\1 ", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i27__DOT____031), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i27.varInsert(__Vfinal,"\\2 ", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i27__DOT____032), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i27.varInsert(__Vfinal,"\\3 ", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i27__DOT____033), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i27.varInsert(__Vfinal,"\\4 ", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i27__DOT____034), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i27.varInsert(__Vfinal,"\\5 ", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i27__DOT____035), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i27.varInsert(__Vfinal,"\\6 ", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i27__DOT____036), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i27.varInsert(__Vfinal,"my_lut", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i27__DOT__my_lut), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,2 ,13,0 ,0,127);
        __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i27.varInsert(__Vfinal,"out", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i27__DOT__out), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,13,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i27.varInsert(__Vfinal,"temp", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i27__DOT__temp), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,6,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i28.varInsert(__Vfinal,"\\0 ", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i28__DOT____030), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i28.varInsert(__Vfinal,"\\1 ", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i28__DOT____031), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i28.varInsert(__Vfinal,"\\2 ", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i28__DOT____032), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i28.varInsert(__Vfinal,"\\3 ", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i28__DOT____033), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i28.varInsert(__Vfinal,"\\4 ", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i28__DOT____034), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i28.varInsert(__Vfinal,"\\5 ", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i28__DOT____035), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i28.varInsert(__Vfinal,"\\6 ", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i28__DOT____036), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i28.varInsert(__Vfinal,"my_lut", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i28__DOT__my_lut), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,2 ,13,0 ,0,127);
        __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i28.varInsert(__Vfinal,"out", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i28__DOT__out), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,13,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i28.varInsert(__Vfinal,"temp", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i28__DOT__temp), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,6,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i29.varInsert(__Vfinal,"\\0 ", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i29__DOT____030), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i29.varInsert(__Vfinal,"\\1 ", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i29__DOT____031), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i29.varInsert(__Vfinal,"\\2 ", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i29__DOT____032), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i29.varInsert(__Vfinal,"\\3 ", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i29__DOT____033), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i29.varInsert(__Vfinal,"\\4 ", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i29__DOT____034), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i29.varInsert(__Vfinal,"\\5 ", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i29__DOT____035), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i29.varInsert(__Vfinal,"\\6 ", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i29__DOT____036), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i29.varInsert(__Vfinal,"my_lut", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i29__DOT__my_lut), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,2 ,13,0 ,0,127);
        __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i29.varInsert(__Vfinal,"out", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i29__DOT__out), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,13,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__LUT_SEG_DECODER_i29.varInsert(__Vfinal,"temp", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__LUT_SEG_DECODER_i29__DOT__temp), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,6,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__Mux_2x1_NBits_i10.varInsert(__Vfinal,"Bits", const_cast<void*>(static_cast<const void*>(&(TOP.FrenchRepublicanCalendarAlarmClock__DOT__Mux_2x1_NBits_i10__DOT__Bits))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__Mux_2x1_NBits_i10.varInsert(__Vfinal,"in_0", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__Mux_2x1_NBits_i10__DOT__in_0), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__Mux_2x1_NBits_i10.varInsert(__Vfinal,"in_1", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__Mux_2x1_NBits_i10__DOT__in_1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__Mux_2x1_NBits_i10.varInsert(__Vfinal,"out", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__Mux_2x1_NBits_i10__DOT__out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__Mux_2x1_NBits_i10.varInsert(__Vfinal,"sel", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__Mux_2x1_NBits_i10__DOT__sel), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,0,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__Mux_2x1_NBits_i11.varInsert(__Vfinal,"Bits", const_cast<void*>(static_cast<const void*>(&(TOP.FrenchRepublicanCalendarAlarmClock__DOT__Mux_2x1_NBits_i11__DOT__Bits))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__Mux_2x1_NBits_i11.varInsert(__Vfinal,"in_0", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__Mux_2x1_NBits_i11__DOT__in_0), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,6,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__Mux_2x1_NBits_i11.varInsert(__Vfinal,"in_1", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__Mux_2x1_NBits_i11__DOT__in_1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,6,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__Mux_2x1_NBits_i11.varInsert(__Vfinal,"out", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__Mux_2x1_NBits_i11__DOT__out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,6,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__Mux_2x1_NBits_i11.varInsert(__Vfinal,"sel", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__Mux_2x1_NBits_i11__DOT__sel), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,0,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__Mux_2x1_NBits_i6.varInsert(__Vfinal,"Bits", const_cast<void*>(static_cast<const void*>(&(TOP.FrenchRepublicanCalendarAlarmClock__DOT__Mux_2x1_NBits_i6__DOT__Bits))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__Mux_2x1_NBits_i6.varInsert(__Vfinal,"in_0", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__Mux_2x1_NBits_i6__DOT__in_0), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,6,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__Mux_2x1_NBits_i6.varInsert(__Vfinal,"in_1", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__Mux_2x1_NBits_i6__DOT__in_1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,6,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__Mux_2x1_NBits_i6.varInsert(__Vfinal,"out", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__Mux_2x1_NBits_i6__DOT__out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,6,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__Mux_2x1_NBits_i6.varInsert(__Vfinal,"sel", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__Mux_2x1_NBits_i6__DOT__sel), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,0,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__Mux_2x1_NBits_i7.varInsert(__Vfinal,"Bits", const_cast<void*>(static_cast<const void*>(&(TOP.FrenchRepublicanCalendarAlarmClock__DOT__Mux_2x1_NBits_i7__DOT__Bits))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__Mux_2x1_NBits_i7.varInsert(__Vfinal,"in_0", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__Mux_2x1_NBits_i7__DOT__in_0), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__Mux_2x1_NBits_i7.varInsert(__Vfinal,"in_1", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__Mux_2x1_NBits_i7__DOT__in_1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__Mux_2x1_NBits_i7.varInsert(__Vfinal,"out", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__Mux_2x1_NBits_i7__DOT__out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__Mux_2x1_NBits_i7.varInsert(__Vfinal,"sel", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__Mux_2x1_NBits_i7__DOT__sel), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,0,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__Mux_2x1_NBits_i8.varInsert(__Vfinal,"Bits", const_cast<void*>(static_cast<const void*>(&(TOP.FrenchRepublicanCalendarAlarmClock__DOT__Mux_2x1_NBits_i8__DOT__Bits))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__Mux_2x1_NBits_i8.varInsert(__Vfinal,"in_0", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__Mux_2x1_NBits_i8__DOT__in_0), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__Mux_2x1_NBits_i8.varInsert(__Vfinal,"in_1", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__Mux_2x1_NBits_i8__DOT__in_1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__Mux_2x1_NBits_i8.varInsert(__Vfinal,"out", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__Mux_2x1_NBits_i8__DOT__out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__Mux_2x1_NBits_i8.varInsert(__Vfinal,"sel", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__Mux_2x1_NBits_i8__DOT__sel), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,0,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__Mux_2x1_NBits_i9.varInsert(__Vfinal,"Bits", const_cast<void*>(static_cast<const void*>(&(TOP.FrenchRepublicanCalendarAlarmClock__DOT__Mux_2x1_NBits_i9__DOT__Bits))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__Mux_2x1_NBits_i9.varInsert(__Vfinal,"in_0", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__Mux_2x1_NBits_i9__DOT__in_0), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__Mux_2x1_NBits_i9.varInsert(__Vfinal,"in_1", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__Mux_2x1_NBits_i9__DOT__in_1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__Mux_2x1_NBits_i9.varInsert(__Vfinal,"out", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__Mux_2x1_NBits_i9__DOT__out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_FrenchRepublicanCalendarAlarmClock__Mux_2x1_NBits_i9.varInsert(__Vfinal,"sel", &(TOP.FrenchRepublicanCalendarAlarmClock__DOT__Mux_2x1_NBits_i9__DOT__sel), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"ALARM_DAYS", &(TOP.ALARM_DAYS), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,1 ,3,0);
        __Vscope_TOP.varInsert(__Vfinal,"ALARM_EN", &(TOP.ALARM_EN), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"ALARM_HOURS", &(TOP.ALARM_HOURS), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,1 ,3,0);
        __Vscope_TOP.varInsert(__Vfinal,"ALARM_MINUTES", &(TOP.ALARM_MINUTES), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,1 ,6,0);
        __Vscope_TOP.varInsert(__Vfinal,"ALARM_MONTHS", &(TOP.ALARM_MONTHS), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,1 ,3,0);
        __Vscope_TOP.varInsert(__Vfinal,"ALARM_WEEKS", &(TOP.ALARM_WEEKS), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,1 ,1,0);
        __Vscope_TOP.varInsert(__Vfinal,"BUZZ", &(TOP.BUZZ), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"CLK", &(TOP.CLK), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"CLR", &(TOP.CLR), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"DAYS", &(TOP.DAYS), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,1 ,3,0);
        __Vscope_TOP.varInsert(__Vfinal,"DAY_ADV", &(TOP.DAY_ADV), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"HOURS", &(TOP.HOURS), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,1 ,3,0);
        __Vscope_TOP.varInsert(__Vfinal,"HR_ADV", &(TOP.HR_ADV), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"MINUTES", &(TOP.MINUTES), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,1 ,6,0);
        __Vscope_TOP.varInsert(__Vfinal,"MIN_ADV", &(TOP.MIN_ADV), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"MONTHS", &(TOP.MONTHS), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,1 ,3,0);
        __Vscope_TOP.varInsert(__Vfinal,"MONTH_ADV", &(TOP.MONTH_ADV), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"SECONDS", &(TOP.SECONDS), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,1 ,6,0);
        __Vscope_TOP.varInsert(__Vfinal,"SEG_DAYS", &(TOP.SEG_DAYS), false, VLVT_UINT16,VLVD_OUT|VLVF_PUB_RW,1 ,13,0);
        __Vscope_TOP.varInsert(__Vfinal,"SEG_HOURS", &(TOP.SEG_HOURS), false, VLVT_UINT16,VLVD_OUT|VLVF_PUB_RW,1 ,13,0);
        __Vscope_TOP.varInsert(__Vfinal,"SEG_MINUTES", &(TOP.SEG_MINUTES), false, VLVT_UINT16,VLVD_OUT|VLVF_PUB_RW,1 ,13,0);
        __Vscope_TOP.varInsert(__Vfinal,"SEG_MONTHS", &(TOP.SEG_MONTHS), false, VLVT_UINT16,VLVD_OUT|VLVF_PUB_RW,1 ,13,0);
        __Vscope_TOP.varInsert(__Vfinal,"SEG_SECONDS", &(TOP.SEG_SECONDS), false, VLVT_UINT16,VLVD_OUT|VLVF_PUB_RW,1 ,13,0);
        __Vscope_TOP.varInsert(__Vfinal,"SEG_WEEKS", &(TOP.SEG_WEEKS), false, VLVT_UINT16,VLVD_OUT|VLVF_PUB_RW,1 ,13,0);
        __Vscope_TOP.varInsert(__Vfinal,"SEG_YEARS", &(TOP.SEG_YEARS), false, VLVT_UINT16,VLVD_OUT|VLVF_PUB_RW,1 ,13,0);
        __Vscope_TOP.varInsert(__Vfinal,"SETUP_ALARM", &(TOP.SETUP_ALARM), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"SETUP_TIME", &(TOP.SETUP_TIME), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"WEEKS", &(TOP.WEEKS), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,1 ,1,0);
        __Vscope_TOP.varInsert(__Vfinal,"WEEK_ADV", &(TOP.WEEK_ADV), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"YEARS", &(TOP.YEARS), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,1 ,3,0);
        __Vscope_TOP.varInsert(__Vfinal,"YEAR_ADV", &(TOP.YEAR_ADV), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0);
    }
}
