// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design implementation internals
// See VFrenchRepublicanCalendarAlarmClock.h for the primary calling header

#include "VFrenchRepublicanCalendarAlarmClock__pch.h"
#include "VFrenchRepublicanCalendarAlarmClock__Syms.h"
#include "VFrenchRepublicanCalendarAlarmClock___024root.h"

// Parameter definitions for VFrenchRepublicanCalendarAlarmClock___024root
constexpr IData/*31:0*/ VFrenchRepublicanCalendarAlarmClock___024root::FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i0__DOT__Bits;
constexpr IData/*31:0*/ VFrenchRepublicanCalendarAlarmClock___024root::FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i1__DOT__Bits;
constexpr IData/*31:0*/ VFrenchRepublicanCalendarAlarmClock___024root::FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i2__DOT__Bits;
constexpr IData/*31:0*/ VFrenchRepublicanCalendarAlarmClock___024root::FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i3__DOT__Bits;
constexpr IData/*31:0*/ VFrenchRepublicanCalendarAlarmClock___024root::FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i4__DOT__Bits;
constexpr IData/*31:0*/ VFrenchRepublicanCalendarAlarmClock___024root::FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i5__DOT__Bits;
constexpr IData/*31:0*/ VFrenchRepublicanCalendarAlarmClock___024root::FrenchRepublicanCalendarAlarmClock__DOT__Mux_2x1_NBits_i6__DOT__Bits;
constexpr IData/*31:0*/ VFrenchRepublicanCalendarAlarmClock___024root::FrenchRepublicanCalendarAlarmClock__DOT__Mux_2x1_NBits_i7__DOT__Bits;
constexpr IData/*31:0*/ VFrenchRepublicanCalendarAlarmClock___024root::FrenchRepublicanCalendarAlarmClock__DOT__Mux_2x1_NBits_i8__DOT__Bits;
constexpr IData/*31:0*/ VFrenchRepublicanCalendarAlarmClock___024root::FrenchRepublicanCalendarAlarmClock__DOT__Mux_2x1_NBits_i9__DOT__Bits;
constexpr IData/*31:0*/ VFrenchRepublicanCalendarAlarmClock___024root::FrenchRepublicanCalendarAlarmClock__DOT__Mux_2x1_NBits_i10__DOT__Bits;
constexpr IData/*31:0*/ VFrenchRepublicanCalendarAlarmClock___024root::FrenchRepublicanCalendarAlarmClock__DOT__Mux_2x1_NBits_i11__DOT__Bits;
constexpr IData/*31:0*/ VFrenchRepublicanCalendarAlarmClock___024root::FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i12__DOT__Bits;
constexpr IData/*31:0*/ VFrenchRepublicanCalendarAlarmClock___024root::FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i13__DOT__Bits;
constexpr IData/*31:0*/ VFrenchRepublicanCalendarAlarmClock___024root::FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i14__DOT__Bits;
constexpr IData/*31:0*/ VFrenchRepublicanCalendarAlarmClock___024root::FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i15__DOT__Bits;
constexpr IData/*31:0*/ VFrenchRepublicanCalendarAlarmClock___024root::FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i16__DOT__Bits;
constexpr IData/*31:0*/ VFrenchRepublicanCalendarAlarmClock___024root::FrenchRepublicanCalendarAlarmClock__DOT__DIG_Counter_Nbit_i17__DOT__Bits;
constexpr IData/*31:0*/ VFrenchRepublicanCalendarAlarmClock___024root::FrenchRepublicanCalendarAlarmClock__DOT__CompUnsigned_i18__DOT__Bits;
constexpr IData/*31:0*/ VFrenchRepublicanCalendarAlarmClock___024root::FrenchRepublicanCalendarAlarmClock__DOT__CompUnsigned_i19__DOT__Bits;
constexpr IData/*31:0*/ VFrenchRepublicanCalendarAlarmClock___024root::FrenchRepublicanCalendarAlarmClock__DOT__CompUnsigned_i22__DOT__Bits;
constexpr IData/*31:0*/ VFrenchRepublicanCalendarAlarmClock___024root::FrenchRepublicanCalendarAlarmClock__DOT__CompUnsigned_i23__DOT__Bits;
constexpr IData/*31:0*/ VFrenchRepublicanCalendarAlarmClock___024root::FrenchRepublicanCalendarAlarmClock__DOT__CompUnsigned_i24__DOT__Bits;


void VFrenchRepublicanCalendarAlarmClock___024root___ctor_var_reset(VFrenchRepublicanCalendarAlarmClock___024root* vlSelf);

VFrenchRepublicanCalendarAlarmClock___024root::VFrenchRepublicanCalendarAlarmClock___024root(VFrenchRepublicanCalendarAlarmClock__Syms* symsp, const char* v__name)
    : VerilatedModule{v__name}
    , vlSymsp{symsp}
 {
    // Reset structure values
    VFrenchRepublicanCalendarAlarmClock___024root___ctor_var_reset(this);
}

void VFrenchRepublicanCalendarAlarmClock___024root::__Vconfigure(bool first) {
    (void)first;  // Prevent unused variable warning
}

VFrenchRepublicanCalendarAlarmClock___024root::~VFrenchRepublicanCalendarAlarmClock___024root() {
}
